// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })
import styles from '@/styles/Home.module.css'
import fetcher from '@/utils/fetcher'
import getGoogleOAuthURL from '@/utils/getGoogleUrl'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import useSWR from 'swr'

interface User {
  _id: string
  email: string
  name: string
  createdAt: Date
  updatedAt: Date
  __v: number
  session: string
  iat: number
  exp: number
}

// export default function Home({ fallbackData }) {
const Home: NextPage<{ fallbackData: User }> = ({ fallbackData }) => {
  console.log('fallbackData', fallbackData) // ! null -> fixed `url`
  // const { data, error } = useSWR<User>( // ! No overload matches this call.
  const { data, error } = useSWR<User | null>(
    `
  ${process.env.NEXT_PUBLIC_SERVER_URL}/api/me
`,
    fetcher,
    // fallbackData
    { fallbackData }
  )

  // ! GET http://localhost:1337/api/me 403 (Forbidden)
  // ! after logged in:
  // Welcome, you are logged in
  // {"_id":"640eff7aa7cf4d1304677aa4","email":"test2@test.com","name":"test2","createdAt":"2023-03-13T10:48:26.966Z","updatedAt":"2023-03-13T10:48:26.966Z","__v":0,"session":"640f2d57a7cf4d1304677aad","iat":1678716247,"exp":1678717147}

  if (data) {
    return (
      <main
        style={{
          padding: '2rem',
          // display: 'flex',
          // flexDirection: 'column',
          // alignItems: 'center',
          // gap: '1rem',
        }}
      >
        <h2
          style={{
            color: '#fc4e77',
            textAlign: 'center',
          }}
        >
          Welcome <span style={{ color: 'white' }}>{data.name}</span>, you are logged in
        </h2>
        <div style={{ marginTop: '2rem', wordWrap: 'break-word' }}>
          {JSON.stringify(data)}
        </div>
      </main>
    )
  }

  return (
    <>
      <Head>
        <title>Home - REST API 1 Frontend - Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        style={{
          padding: '2rem',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '1rem',
        }}
      >
        <h1>Home page</h1>
        <h2
          style={{
            color: '#fc4e77',
            marginTop: '1rem',
          }}
        >
          Please login
        </h2>
        <div className='login-options'>
          <div
            style={{
              display: 'flex',
              gap: '1rem',
            }}
          >
            <Link href='/login' className='login-link'>
              Login
            </Link>
            <Link href='/register' className='login-link'>
              Register
            </Link>
          </div>
          <a
            href={getGoogleOAuthURL()}
            // style={{
            //   backgroundColor: '#8d22b7',
            //   padding: '0.7rem',
            //   borderRadius: '8px',
            // }}
            className='link-google-login'
          >
            Login with Google
          </a>
        </div>
      </main>
    </>
  )
}

export default Home

// export async function getServerSideProps() {
export const getServerSideProps: GetServerSideProps = async (context) => {
  // console.log('getServerSideProps')
  const headers = context.req.headers // pass headers to fetcher func.

  const data = await fetcher(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/me`, headers)
  return {
    props: {
      fallbackData: data,
    },
  }
}
// ! Server Error AxiosError: Request failed with status code 404
// ! Uncaught AxiosError: Request failed with status code 404
// ! GET http://localhost:3000/ 500 (Internal Server Error)
